### PR TITLE
Compatibility with dplyr 1.1.0

### PR DESCRIPTION
**Pull request by lionel-**
- Use `all_of()` with external variables to silence a warning
- Use `[[` to subset last column instead of `dplyr::last()`. The latter now retrieves the last row instead of the last column.

We plan to release on January 27. These changes are compatible with both CRAN and dev dplyr. A pre-emptive release would be helpful if possible. Thanks!

### CODE REVIEW

**Review by andrewzm — COMMENTED** [review]
Hello, we actually want to return the last row here if the argument were to be a data frame (in our case, the arguments are vectors, so we just return the last element). 

So I assume in this case we should keep on using last()?

**Comment by lionel-** [comment]
> So I assume in this case we should keep on using last()?

yup maybe so, but I believe this breaks your unit tests. Can you please take a look at this then?

**Comment by andrewzm** [comment]
Got it, the new last() function behaves unexpectedly with xts objects (it's OK with POSIX objects). So I just converted the xts to a vector before using last() which works well for me.

I've made my own changes and pushed on github since some of the modifications are slightly different, so I'll close this pull request. All should work well after next push to CRAN (probably in January too). Thanks for sorting this out in advance!

**Comment by lionel-** [comment]
Thanks!

**Pull request closed without merging**
